name: Daily Screenshot

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run screenshot script
        run: node screenshot.js

      - name: Commit screenshots
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          
          if [ -d "screenshots" ]; then
            git add screenshots/*
            git commit -m "Add screenshot $(date +'%Y-%m-%d')" || echo "No changes"
            git push
          else
            echo "No screenshots folder yet"
          fi
